//
//  ExhibitModels.swift
//  FileExhibitsLoader
//
//  Created by Mitya_Potemkin on 4/14/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public struct Exhibit: Decodable {
    public var title: String = ""
    public var images: [String] = []

}
