//
//  ExhibitionsListPresenter.swift
//  UranTestTask
//
//  Created by Mac on 4/14/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FileExhibitsLoader

protocol ExhibitionsListPresentationLogic {
    func presentData(response: ExhibitionsList.Model.Response)
}

class ExhibitionsListPresenter: ExhibitionsListPresentationLogic {
    weak var viewController: ExhibitionsListDisplayLogic?
    
    
    func presentData(response: ExhibitionsList.Model.Response) {
        //TEST MODE
//        var objs = [ExhibitionsList.Model.ViewModel.Object]()
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 5s", imagesUrl: ["https://upload.wikimedia.org/wikipedia/commons/f/fd/IPhone_5S.jpg","http://img01.ibnlive.in/ibnlive/uploads/2015/12/apple-iphone5s-151215.jpg","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5cv-olMz3XKQNhQP4SpwiwqtiDreaBlpESHdCDc6Jm5GjHzRsHcxXrqAI"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 6s", imagesUrl: ["https://c1.staticflickr.com/2/1665/26162561181_01148e99ee_b.jpg","https://img1.ibay.com.mv/is1/full/2017/11/item_2028958_545.jpg","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8jIpCOU94HxZEab_vJdl9nGsaAOO18dqq2BXt_L2-PnWhroi", "https://c1.staticflickr.com/4/3907/15102682838_25e6c90469_b.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnMHHcDnMlsrtPpZmfLjQqlJXQNNEvTTg7WWMGcbOHOvxdVUoi"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        objs.append(ExhibitionsList.Model.ViewModel.Object(name: "iPhone 7", imagesUrl: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQYu7fKAuYLwQCiilRNCv_wzVZbOpLGsrRzQA7prdgToCiBzsQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS8lca49LZGvPUtJxrof6DuzvjgKiR_0Nei_b8zeR-3uq1kzyLQ", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTko9xdQRKcdJrshSPWCjTtml9eSKiABSN--VhC5YV8MMASVRfgYw", "https://cdn.pixabay.com/photo/2014/12/10/12/27/iphone-563070_960_720.jpg"]))
//        var viewModel = ExhibitionsList.Model.ViewModel(objects: objs)

        var viewModel = ExhibitionsList.Model.ViewModel()
        viewModel.objects = [ExhibitionsList.Model.ViewModel.Object]()
        for item in response.exhibits{
            let object = ExhibitionsList.Model.ViewModel.Object(name: item.title, imagesUrl: item.images)
            viewModel.objects?.append(object)
        }
        viewController?.displayObjectsList(viewModel: viewModel)
    }
}
