//
//  ExhibitionsListRouter.swift
//  UranTestTask
//
//  Created by Mac on 4/14/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ExhibitionsListRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ExhibitionsListDataPassing {
    var dataStore: ExhibitionsListDataStore? { get }
}

class ExhibitionsListRouter: NSObject, ExhibitionsListRoutingLogic, ExhibitionsListDataPassing {
    weak var viewController: ExhibitionsListViewController?
    var dataStore: ExhibitionsListDataStore?
    
    // MARK: Routing
    
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    // MARK: Navigation
    
//    func navigateToSomewhere(source: ExhibitionsListViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
    
    // MARK: Passing data
    
//    func passDataToSomewhere(source: ExhibitionsListDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
