//
//  ExhibitionsListInteractor.swift
//  UranTestTask
//
//  Created by Mac on 4/14/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExhibitionsListBusinessLogic {
    func getObjectsList()
}

protocol ExhibitionsListDataStore {
    //var name: String { get set }
}

class ExhibitionsListInteractor: ExhibitionsListBusinessLogic, ExhibitionsListDataStore {
    var presenter: ExhibitionsListPresentationLogic?
    var worker: ExhibitionsListWorker?
    
    // MARK: Do something
    
    func getObjectsList() {
//        TEST MODE
//        presenter?.presentData(response: ExhibitionsList.Model.Response(exhibits: [Exhibit]()))

        worker = ExhibitionsListWorker()
        ProgressLoader.show()
        worker?.fetchExhibits(completion: { (response) in
            ProgressLoader.hide {
                self.presenter?.presentData(response: ExhibitionsList.Model.Response(exhibits: response))
            }
        })
    }
}
