//
//  ExhibitionsListModels.swift
//  UranTestTask
//
//  Created by Mac on 4/14/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FileExhibitsLoader

enum ExhibitionsList {
    // MARK: Use cases
    
    enum Model {
        struct Request {
        }
        
        struct Response {
            var exhibits: [Exhibit]
        }
        
        struct ViewModel {
            struct Object {
                var name: String?
                var imagesUrl: [String]?
            }
            var objects: [Object]?

        }
    }
}
